export const API_ENDPOINTS = {
  auth: {
    login: 'auth/login',
    refresh: 'auth/refresh',
    logout: 'auth/logout',
    forgotPassword: 'auth/forgot-password',
    resetPassword: (token: string) => `auth/reset-password/${token}`,
    changePassword: 'auth/change-password',
    me: 'auth/me',
  },
  users: {
    list: 'users',
    detail: (id: string) => `users/${id}`,
    profile: 'users/profile',
    status: (id: string) => `users/status/${id}`,
    roles: (id: string) => `users/roles/${id}`,
  },
  blog: {
    list: 'blog',
    detail: (slug: string) => `blog/${slug}`,
    categories: 'blog/categories',
    adminList: 'admin/blog',
    adminDetail: (id: string) => `admin/blog/${id}`,
    adminCreate: 'admin/blog',
    adminUpdate: (id: string) => `admin/blog/${id}`,
    adminDelete: (id: string) => `admin/blog/${id}`,
    adminPublish: (id: string) => `admin/blog/publish/${id}`,
    adminCategories: 'admin/blog/categories',
  },
  services: {
    list: 'services',
    detail: (slug: string) => `services/${slug}`,
    categories: 'services/categories',
    adminList: 'admin/services',
    adminCreate: 'admin/services',
    adminUpdate: (id: string) => `admin/services/${id}`,
    adminDelete: (id: string) => `admin/services/${id}`,
  },
  solutions: {
    list: 'solutions',
    detail: (slug: string) => `solutions/${slug}`,
    adminList: 'admin/solutions',
    adminCreate: 'admin/solutions',
    adminUpdate: (id: string) => `admin/solutions/${id}`,
    adminDelete: (id: string) => `admin/solutions/${id}`,
  },
  products: {
    list: 'products',
    detail: (slug: string) => `products/${slug}`,
    adminList: 'admin/products',
    adminCreate: 'admin/products',
    adminUpdate: (id: string) => `admin/products/${id}`,
    adminDelete: (id: string) => `admin/products/${id}`,
  },
  portfolio: {
    list: 'portfolio',
    detail: (slug: string) => `portfolio/${slug}`,
    featured: 'portfolio/featured',
    adminList: 'admin/portfolio',
    adminCreate: 'admin/portfolio',
    adminUpdate: (id: string) => `admin/portfolio/${id}`,
    adminDelete: (id: string) => `admin/portfolio/${id}`,
  },
  caseStudies: {
    list: 'case-studies',
    detail: (slug: string) => `case-studies/${slug}`,
    adminList: 'admin/case-studies',
    adminCreate: 'admin/case-studies',
    adminUpdate: (id: string) => `admin/case-studies/${id}`,
    adminDelete: (id: string) => `admin/case-studies/${id}`,
  },
  testimonials: {
    list: 'testimonials',
    adminList: 'admin/testimonials',
    adminCreate: 'admin/testimonials',
    adminUpdate: (id: string) => `admin/testimonials/${id}`,
    adminDelete: (id: string) => `admin/testimonials/${id}`,
    adminApprove: (id: string) => `admin/testimonials/${id}/approve`,
  },
  leads: {
    submit: 'leads',
    adminList: 'admin/leads',
    adminDetail: (id: string) => `admin/leads/${id}`,
    adminUpdate: (id: string) => `admin/leads/${id}`,
    adminStatus: (id: string) => `admin/leads/${id}/status`,
    adminAssign: (id: string) => `admin/leads/${id}/assign`,
    adminConvert: (id: string) => `admin/leads/${id}/convert`,
    adminExport: 'admin/leads/export',
  },
  consultations: {
    book: 'consultations',
    adminList: 'admin/consultations',
    adminDetail: (id: string) => `admin/consultations/${id}`,
    adminConfirm: (id: string) => `admin/consultations/${id}/confirm`,
  },
  contact: {
    submit: 'contact',
    adminList: 'admin/contact',
    adminDetail: (id: string) => `admin/contact/${id}`,
  },
  careers: {
    list: 'careers',
    detail: (slug: string) => `careers/${slug}`,
    adminList: 'admin/careers',
    adminCreate: 'admin/careers',
    adminUpdate: (id: string) => `admin/careers/${id}`,
    adminDelete: (id: string) => `admin/careers/${id}`,
  },
  applications: {
    submit: 'applications',
    adminList: 'admin/applications',
    adminDetail: (id: string) => `admin/applications/${id}`,
  },
  newsletter: {
    subscribe: 'newsletter/subscribe',
    unsubscribe: 'newsletter/unsubscribe',
    adminList: 'admin/newsletter',
    adminExport: 'admin/newsletter/export',
  },
  media: {
    adminList: 'admin/media',
    upload: 'admin/media/upload',
    delete: (id: string) => `admin/media/${id}`,
  },
  notifications: {
    list: 'notifications',
    unreadCount: 'notifications/unread-count',
    markRead: (id: string) => `notifications/${id}/read`,
    markAllRead: 'notifications/read-all',
    broadcast: 'admin/notifications/broadcast',
  },
  analytics: {
    track: 'analytics/track',
    dashboard: 'admin/analytics/dashboard',
    pageViews: 'admin/analytics/page-views',
    trafficSources: 'admin/analytics/traffic-sources',
  },
  audit: {
    adminList: 'admin/audit',
    adminDetail: (id: string) => `admin/audit/${id}`,
  },
  settings: {
    public: 'settings/public',
    adminAll: 'admin/settings',
    adminGroup: (group: string) => `admin/settings/${group}`,
  },
  health: {
    status: 'health',
    detailed: 'health/detailed',
  },
} as const;
